groups:
  - name: example
    rules:
      - alert: HighCPUUsage
        expr: (100 - avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)                   > 50
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 50% on instance {{ $labels.instance }}"
          value: "{{ $value }}"
